import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#e6f6fd",
        alignItems: "center",
        justifyContent: "center",
        paddingTop: 50,
    },
    glassCard: {
        width: width * 0.9,
        padding: 24,
        borderRadius: 30,
        backgroundColor: "rgba(255,255,255,0.3)",
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.4)",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
        marginBottom: 20,
    },
    title: {
        fontSize: 26,
        fontWeight: "700",
        color: "#1e3a5f",
        marginBottom: 20,
        textAlign: "center",
    },
    notificationBox: {
        marginTop: 16,
        padding: 20,
        borderRadius: 20,
        backgroundColor: "#ffffffcc",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.4)",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.05,
        shadowRadius: 12,
        elevation: 6,
    },
    notificationLabel: {
        fontSize: 16,
        fontWeight: "600",
        color: "#0080ff",
        marginBottom: 10,
        textAlign: "center",
    },
    notificationText: {
        fontSize: 15,
        color: "#333",
        marginBottom: 6,
    },
    noNotification: {
        fontSize: 16,
        fontStyle: "italic",
        color: "#666",
        marginTop: 12,
        textAlign: "center",
    },
    bottomTabBar: {
        position: "absolute",
        bottom: 20,
        left: 20,
        right: 20,
        height: 70,
        backgroundColor: "#ffffff",
        borderRadius: 35,
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 15,
    },
    historyContainer: {
        width: width * 0.9,
        maxHeight: height * 0.4,
        backgroundColor: "#ffffff",
        borderRadius: 20,
        padding: 20,
        marginTop: 10,
        marginBottom: 30,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    historyTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#007bff",
        marginBottom: 12,
    },
    historyItem: {
        backgroundColor: "#f2f9ff",
        borderRadius: 12,
        padding: 10,
        marginBottom: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    historyText: {
        fontSize: 15,
        color: "#333",
    },
    noHistory: {
        fontSize: 15,
        fontStyle: "italic",
        color: "#666",
        textAlign: "center",
    },
});

export default styles;
