import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e6f6fd",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 50,
  },
  glassCard: {
    width: width * 0.9,
    padding: 24,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.4)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
    marginBottom: 20,
  },
  title: {
    fontSize: 26,
    fontWeight: "700",
    color: "#1e3a5f",
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    height: 55,
    borderRadius: 20,
    backgroundColor: "#ffffffaa",
    paddingHorizontal: 20,
    marginBottom: 20,
    color: "#333",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 3,
  },
  buttonPrimary: {
    backgroundColor: "#00bcd4",
    paddingVertical: 14,
    borderRadius: 20,
    alignItems: "center",
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  buttonPrimaryText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  micButton: {
    backgroundColor: "#0072ff",
    padding: 14,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  resultBox: {
    backgroundColor: "#ffffff",
    padding: 18,
    marginTop: 10,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    width: width * 0.85,
    alignSelf: "center",
  },
  resultText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#007f5f",
    textAlign: "center",
  },
  activityIndicator: {
    marginTop: 20,
  },
  bottomTabBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    height: 70,
    backgroundColor: "#ffffff",
    borderRadius: 35,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 15,
  },
});
export default styles;
